#Retorna todos usuarios
GET http://localhost:3000/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJiaW5pIiwiZW1haWwiOiJiaW5pZ29uQGdtYWlsLmNvbSIsImlhdCI6MTcwODc4MzU1MCwiZXhwIjoxNzA4Nzg3MTUwfQ.-AVSDh0eFe23EQjOMznlwTMGFw2apIvMRoHgd9isI8o

###Criar um usuario
POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
    "username": "gutocugnier",
    "email": "guto@gmail.com",
    "password": "!Guto123"
}

###Busca um usuario pelo id
GET http://localhost:3000/users/2 HTTP/1.1

###Login
POST  http://localhost:3000/auth/login HTTP/1.1
content-type: application/json

{
    "username": "gutocugnier",
    "password": "$2b$10$SX3NERXpf/j0ZvIK00zcK.4KnQ2kuF1.aiGdccWdt5txvxyzy/Dsu"
}



###Cria um post
POST http://localhost:3000/posts HTTP/1.1
content-type: application/json

{
    "title": "Post 4",
    "body": "Conteudo do post 3",
    "user": 1
}

###Retorna todos posts
GET http://localhost:3000/posts HTTP/1.1


###Retorna um post pelo id
GET http://localhost:3000/posts/2 HTTP/1.1
